services:
  nginx:
    image: nginx:latest
    ports:
      - '8081:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-demo-network
  php-fpm:
    build:
      context: ./app
    volumes:
      - ./app:/var/www/html
    networks:
      - php-demo-network

# Containers on the same network don't need to expose any ports in order to
# communicate with each other. That't why we don't specify ports in php service.
networks:
  php-demo-network:
    driver: bridge

